"""
Django settings for mharetech project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_env_file(path: Path) -> None:
    """Load KEY=VALUE lines into os.environ (used by manage.py and gunicorn)."""
    if not path.is_file():
        return
    for raw in path.read_text(encoding='utf-8').splitlines():
        line = raw.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, _, value = line.partition('=')
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key and key not in os.environ:
            os.environ[key] = value


_load_env_file(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-g%nx=+_qy^jap3f+yqcz4yad+n%9-ib%(nrpdx&d0s*^045@+b')

DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

ALLOWED_HOSTS = ['mharetech.co.za', 'www.mharetech.co.za', 'sibanye.mharetech.co.za',
                 'internal.mharetech.co.za', 'localhost', '127.0.0.1']
if DEBUG:
    # Allow *.localhost (e.g. internal.localhost) for local subdomain testing.
    ALLOWED_HOSTS.append('.localhost')

CSRF_TRUSTED_ORIGINS = [
    'https://mharetech.co.za',
    'https://www.mharetech.co.za',
    'https://sibanye.mharetech.co.za',
    'https://internal.mharetech.co.za',
]
CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SAMESITE = 'Lax'


# Application definition

INSTALLED_APPS = [
    'django.contrib.sessions',
    'django.contrib.staticfiles',
    'website',
    'internal',
]

# Signed-cookie sessions — no database required (DATABASES is empty).
SESSION_ENGINE = 'django.contrib.sessions.backends.signed_cookies'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # Swaps urlconf + enforces the password gate for the internal.* subdomain.
    'internal.middleware.InternalGateMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mharetech.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': False,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
            ],
        },
    },
]

WSGI_APPLICATION = 'mharetech.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {}

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Africa/Johannesburg'
USE_I18N = False
USE_TZ = True

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    }
}

# Expo lead email (set SMTP_* on production VM)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('SMTP_HOST', '')
EMAIL_PORT = int(os.environ.get('SMTP_PORT', '587'))
# Port 465: SMTP_USE_SSL=True, SMTP_USE_TLS=False
# Port 587: SMTP_USE_TLS=True, SMTP_USE_SSL=False
EMAIL_USE_SSL = os.environ.get('SMTP_USE_SSL', 'False') == 'True'
EMAIL_USE_TLS = os.environ.get('SMTP_USE_TLS', 'False') == 'True'
EMAIL_HOST_USER = os.environ.get('SMTP_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('SMTP_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('EXPO_LEAD_FROM', 'sales@mhareconsulting.co.za')
EXPO_LEAD_TO = os.environ.get('EXPO_LEAD_TO', 'sales@mhareconsulting.co.za')
EXPO_LEAD_FROM = os.environ.get('EXPO_LEAD_FROM', DEFAULT_FROM_EMAIL)

# Internal tools subdomain (internal.mharetech.co.za)
INTERNAL_PASSWORD = os.environ.get('INTERNAL_PASSWORD', '')
INTERNAL_ASSESSMENT_TO = os.environ.get('INTERNAL_ASSESSMENT_TO', EXPO_LEAD_TO)

# Local-dev aid: with no SMTP configured, print emails to the console so the
# assessment form can be exercised end-to-end without a mail server.
if DEBUG and not EMAIL_HOST:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
